name: AI Cost Optimizer

on:
  pull_request:
    branches:
      - main

jobs:
  analyze-cost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Cost Optimizer (DeepSeek)
        env:
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
        run: |
          python main.py &
          
          # Wait for FastAPI server to be ready
          for i in {1..10}; do
              if curl -s http://localhost:8000/health; then
                  break
              fi
              sleep 2
          done

          # Run the analysis
          curl -X POST http://localhost:8000/analyze \
               -H "Content-Type: application/json" \
               -d '{"code": "sample_code"}' > analysis.txt
          cat analysis.txt
